version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unparam
    - zerologlint
  disable:
    - prealloc
  settings:
    gocognit:
      min-complexity: 10
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 10
    nestif:
      min-complexity: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
