language: go

services:
  - docker

go:
  - '1.12.6'

env:
  - GO111MODULE=on

before_install:
  - go get -u golang.org/x/lint/golint

install:
  - go mod vendor

script:
  - make lint
  - make test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make image
    - make publish
  on:
    tags: true
