---
routes:
  - path: /foo
    status: 200
    response: >-
      {
        "id": 123,
        "message": "foo"
      }
  - path: /auth
    status: 401
    response: >-
      {
        "message": "unauthorized"
      }
