---
port: 8080
routes:
  - path: /foo
    status: 200
    response: >-
      {
        "id": 123,
        "message": "foo"
      }
  - path: /foo
    queries:
      - show_deleted
      - true
    status: 200
    response: >-
      {
        "id": 987,
        "message": "bar"
      }
  - path: /auth
    status: 401
    response: >-
      {
        "message": "unauthorized"
      }
  - path: /withResponseHeaders
    headers:
      X-Request-Id: ef835eaf-a658-458b-86ae-d2d771f5e745
      CustomHeader: booyah
    status: 200
    response: >-
      {
        "id": 123,
        "message": "booyah"
      }
