---
port: 8080
routes:
  - path: /foo
    response: >-
      {
        "id": 123,
        "message": "foo"
      }
  - path: /bar
    response: >-
      {
        "id": 321,
        "message": "bar"
      }
