---
port: 8888
routes:
  - path: /foo
    status: 200
    response: >-
      {
        "id": 123,
        "message": "foo"
      }
  - path: /foo
    queries:
      - show_deleted
      - true
    status: 200
    respose: >-
      {
        "id": 987,
        "message": "bar"
      }
  - path: /auth
    status: 401
    response: >-
      {
        "message": "unauthorized"
      }
