services:
    stubby:
        build: .
        command: ["-config", "/config.yaml"]
        ports:
            - 8080:8080
        volumes:
            - ./testing/integration.yaml:/config.yaml

    sut:
        image: golang:1.26
        depends_on:
            - stubby
        
        working_dir: /app
        volumes:
            - ./:/app
        
        environment:
            - STUBBY_ADDR=http://stubby:8080
        command: >
            bash -c "
            until printf '' 2>/dev/null >/dev/tcp/stubby/8080; do echo 'waiting for stubby...'; sleep 1; done &&
            echo '... starting integration tests ...' &&
            go test -v -race ./testing/ --tags=integration &&
            echo '... completed integration tests ...'"